### PR TITLE
Linux aarch64 back to azure

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
Because of this:

https://github.com/conda-forge/pyqtwebkit-feedstock/pull/13#issuecomment-1369642704

**Comment by SrNetoChan** [comment]
I have noticed that we are building this for version 5.15.7, but there are some files already built for 5.21. Not sure what is going on.

**Comment by gillins** [comment]
Where are the files for 5.21? I can't see anything under https://anaconda.org/conda-forge/pyqtwebkit/files

**Comment by SrNetoChan** [comment]
In the second page. It seems to be older...

**Comment by gillins** [comment]
Ah - I didn't see that. Weird. Must have been when we started using the snapshot from Qt. Hopefully these don't get picked up with the pinning being so different now, but we'll have to be alert to the possibility.

**Comment by gillins** [comment]
They are all there this time :smile:

**Pull request merged**
