### PR TITLE
Try to update sip version

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
Seems that qgis 3.26 needs a newer version of sip

**Comment by izahn** [comment]
> 
> Hi! This is the friendly automated conda-forge-webservice.
> 
> It appears you are making a pull request from a branch in your feedstock and not a fork. This procedure will generate a separate build for each push to the branch and is thus not allowed. See our [documentation](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests) for more details.
> 
> Please close this pull request and remake it from a fork of this feedstock.
> 
> Have a great day!
> 

@SrNetoChan better to fork the repo and make PRs from there

**Comment by SrNetoChan** [comment]
Damn. Sorry. I know that. I bumped it on my phone and I thought I was editing my fork

**Comment by SrNetoChan** [comment]
@izahn should I close this and redo it?

**Comment by SrNetoChan** [comment]
@ocefpaf @gillins not sure what to do. Because I didn't use fork, this is already built and available on conda cloud. Is there a way to avoid that once merged it builds again?

Sorry for the mess

**Comment by SrNetoChan** [comment]
I think it's better to merge this and delete the branch, otherwise it keeps building new versions from here instead of master.

**Comment by izahn** [comment]
> I think it's better to merge this and delete the branch, otherwise it keeps building new versions from here instead of master.

I think you can just close it and delete the branch right? I don't think it needs to be merged.

**Comment by SrNetoChan** [comment]
Obviously... Stupid me, I did no relevant changes

**Pull request closed without merging**
