### PR TITLE
Use qt-main 5.15

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
So the patches need updating? Unfortunately I'm not going to be able to have a proper look at this for a couple of weeks... Are you happy to have a go?

**Comment by SrNetoChan** [comment]
> So the patches need updating? Unfortunately I'm not going to be able to have a proper look at this for a couple of weeks... Are you happy to have a go?

@gillins I am trying but my knowledge about all this is very limited and I have troubles understanding were to even begin to investigate or fi things.

**Comment by SrNetoChan** [comment]
One thing I have noticed is that conda-smithy has removed qt from ci support files, which doesn't make sense.

https://github.com/conda-forge/pyqtwebkit-feedstock/pull/5/files#diff-c33a37c49313edd13da48c1d74cdcf290ef18eb3e40e2276e711e1f24384baa0L25

**Comment by hmaarrfk** [comment]
> One thing I have noticed is that conda-smithy has removed qt from ci support files, which doesn't make sense.

I don't think the migrator was live then. You can try to copy the new migrator files in.

For linux, the error seems to be:
```
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/10.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libQt5Core.so: undefined reference to `clock_gettime@GLIBC_2.17'
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/10.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: $PREFIX/lib/libQt5Core.so: undefined reference to `getauxval@GLIBC_2.16'
```

https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=glibc#using-centos-7

FYI: I think we've started to use the new docker images by default.

**Comment by SrNetoChan** [comment]
Superseeded by #6

**Pull request closed without merging**
